[phases.setup]
nixPkgs = ["python312", "cairo", "pango", "gdk-pixbuf", "glib", "gobject-introspection", "libffi", "fontconfig", "freefont_ttf"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build needed'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
