[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build needed'"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
