
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const GmailSetup = lazy(() => import("./pages/GmailSetup.tsx"));
const DropboxSetup = lazy(() => import("./pages/DropboxSetup.tsx"));
const UploadReceipts = lazy(() => import("./pages/UploadReceipts.tsx"));
const SignIn = lazy(() => import("./pages/SignIn.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/sign-in", element: <SignIn />},
	{ path: "/", element: <UserGuard><App /></UserGuard>},
	{ path: "/gmail-setup", element: <UserGuard><GmailSetup /></UserGuard>},
	{ path: "/gmailsetup", element: <UserGuard><GmailSetup /></UserGuard>},
	{ path: "/dropbox-setup", element: <UserGuard><DropboxSetup /></UserGuard>},
	{ path: "/dropboxsetup", element: <UserGuard><DropboxSetup /></UserGuard>},
	{ path: "/upload-receipts", element: <UserGuard><UploadReceipts /></UserGuard>},
	{ path: "/uploadreceipts", element: <UserGuard><UploadReceipts /></UserGuard>},

];
