
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const GmailSetup = lazy(() => import("./pages/GmailSetup.tsx"));
const UploadReceipts = lazy(() => import("./pages/UploadReceipts.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <UserGuard><App /></UserGuard>},
	{ path: "/gmail-setup", element: <GmailSetup />},
	{ path: "/gmailsetup", element: <GmailSetup />},
	{ path: "/upload-receipts", element: <UploadReceipts />},
	{ path: "/uploadreceipts", element: <UploadReceipts />},

];
